name: Trigger Deploy Command
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Command
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.DEPLOY_BRANCH_ACTION }}
          commands: deploy-docs
